### ISSUE TITLE
fails with setuptools >=10.0 

### ISSUE THREAD

**Issue by JasonBoyles** [rackspace-orchestration-templates/ipynb#17]
New version of setup tools breaks the ntlk dependency. Already open issue:

https://github.com/nltk/nltk/issues/824

**Comment by JasonBoyles** [comment]
chef.log: 
```console
# Logfile created on 2015-01-05 20:22:04 +0000 by logger.rb/31641
[2015-01-05T20:22:04+00:00] INFO: Forking chef instance to converge...
[...]
[2015-01-05T20:22:04+00:00] INFO: *** Chef 11.12.8 ***
[2015-01-05T20:22:04+00:00] INFO: Chef-client pid: 3212
[2015-01-05T20:22:07+00:00] INFO: Setting the run_list to ["recipe[apt]", "recipe[build-essential]", "recipe[chef-solo-search]", "recipe[rax-ipynb-auth]", "recipe[ipynb]", "recipe[ipynb::virtenv_launch]", "recipe[ipynb::proxy]", "recipe[rax-firewall]"] from CLI options
[2015-01-05T20:22:07+00:00] INFO: Run List is [recipe[apt], recipe[build-essential], recipe[chef-solo-search], recipe[rax-ipynb-auth], recipe[ipynb], recipe[ipynb::virtenv_launch], recipe[ipynb::proxy], recipe[rax-firewall]]
[2015-01-05T20:22:07+00:00] INFO: Run List expands to [apt, build-essential, chef-solo-search, rax-ipynb-auth, ipynb, ipynb::virtenv_launch, ipynb::proxy, rax-firewall]
[2015-01-05T20:22:07+00:00] INFO: Starting Chef Run for ipynb
[2015-01-05T20:22:07+00:00] INFO: Running start handlers
[2015-01-05T20:22:07+00:00] INFO: Start handlers complete.
[2015-01-05T20:22:07+00:00] INFO: Processing chef_gem[treetop] action install (dynamically defined)
[2015-01-05T20:22:14+00:00] WARN: Cloning resource attributes for package[build-essential] from prior resource (CHEF-3694)
[2015-01-05T20:22:14+00:00] WARN: Previous package[build-essential]: /tmp/heat_chef/b957b1a6-bf3d-4abe-a327-189feac23b14/cookbooks/build-essential/recipes/_debian.rb:24:in `block in from_file'
[2015-01-05T20:22:14+00:00] WARN: Current  package[build-essential]: /tmp/heat_chef/b957b1a6-bf3d-4abe-a327-189feac23b14/cookbooks/ipynb/recipes/default.rb:29:in `block in from_file'
[2015-01-05T20:22:14+00:00] INFO: ohai plugins will be at: /etc/chef/ohai_plugins
[2015-01-05T20:22:14+00:00] INFO: Processing remote_directory[/etc/chef/ohai_plugins for cookbook ohai] action create (ohai::default line 33)
[2015-01-05T20:22:14+00:00] INFO: remote_directory[/etc/chef/ohai_plugins for cookbook ohai] created directory /etc/chef/ohai_plugins
[2015-01-05T20:22:14+00:00] INFO: remote_directory[/etc/chef/ohai_plugins for cookbook ohai] mode changed to 755
[2015-01-05T20:22:14+00:00] INFO: Processing cookbook_file[/etc/chef/ohai_plugins/README] action create (dynamically defined)
[2015-01-05T20:22:14+00:00] INFO: cookbook_file[/etc/chef/ohai_plugins/README] created file /etc/chef/ohai_plugins/README
[2015-01-05T20:22:14+00:00] INFO: cookbook_file[/etc/chef/ohai_plugins/README] updated file contents /etc/chef/ohai_plugins/README
[2015-01-05T20:22:14+00:00] INFO: cookbook_file[/etc/chef/ohai_plugins/README] mode changed to 644
[2015-01-05T20:22:14+00:00] INFO: Processing ohai[custom_plugins] action reload (ohai::default line 47)
[2015-01-05T20:22:19+00:00] INFO: ohai[custom_plugins] reloaded
[2015-01-05T20:22:19+00:00] WARN: Cloning resource attributes for package[libpcre3-dev] from prior resource (CHEF-3694)
[2015-01-05T20:22:19+00:00] WARN: Previous package[libpcre3-dev]: /tmp/heat_chef/b957b1a6-bf3d-4abe-a327-189feac23b14/cookbooks/ipynb/recipes/default.rb:29:in `block in from_file'
[2015-01-05T20:22:19+00:00] WARN: Current  package[libpcre3-dev]: /tmp/heat_chef/b957b1a6-bf3d-4abe-a327-189feac23b14/cookbooks/nginx/recipes/source.rb:53:in `block in from_file'
[2015-01-05T20:22:19+00:00] WARN: Cloning resource attributes for package[libssl-dev] from prior resource (CHEF-3694)
[2015-01-05T20:22:19+00:00] WARN: Previous package[libssl-dev]: /tmp/heat_chef/b957b1a6-bf3d-4abe-a327-189feac23b14/cookbooks/ipynb/recipes/default.rb:29:in `block in from_file'
[2015-01-05T20:22:19+00:00] WARN: Current  package[libssl-dev]: /tmp/heat_chef/b957b1a6-bf3d-4abe-a327-189feac23b14/cookbooks/nginx/recipes/source.rb:53:in `block in from_file'
[2015-01-05T20:22:19+00:00] WARN: Cloning resource attributes for service[nginx] from prior resource (CHEF-3694)
[2015-01-05T20:22:19+00:00] WARN: Current  service[nginx]: /tmp/heat_chef/b957b1a6-bf3d-4abe-a327-189feac23b14/cookbooks/nginx/recipes/source.rb:110:in `from_file'
[2015-01-05T20:22:19+00:00] WARN: Cloning resource attributes for execute[nxdissite default] from prior resource (CHEF-3694)
[2015-01-05T20:22:19+00:00] WARN: Previous execute[nxdissite default]: /tmp/heat_chef/b957b1a6-bf3d-4abe-a327-189feac23b14/cookbooks/nginx/definitions/nginx_site.rb:32:in `block in from_file'
[2015-01-05T20:22:19+00:00] WARN: Current  execute[nxdissite default]: /tmp/heat_chef/b957b1a6-bf3d-4abe-a327-189feac23b14/cookbooks/nginx/definitions/nginx_site.rb:32:in `block in from_file'
[2015-01-05T20:22:19+00:00] INFO: Processing execute[apt-get-update] action run (apt::default line 22)
[2015-01-05T20:22:27+00:00] INFO: execute[apt-get-update] ran successfully
[2015-01-05T20:22:27+00:00] INFO: Processing execute[apt-get update] action nothing (apt::default line 29)
[2015-01-05T20:22:27+00:00] INFO: Processing execute[apt-get autoremove] action nothing (apt::default line 36)
[2015-01-05T20:22:27+00:00] INFO: Processing execute[apt-get autoclean] action nothing (apt::default line 42)
[2015-01-05T20:22:27+00:00] INFO: Processing package[update-notifier-common] action install (apt::default line 48)
[2015-01-05T20:22:30+00:00] INFO: package[update-notifier-common] sending run action to execute[apt-get-update] (immediate)
[2015-01-05T20:22:30+00:00] INFO: Processing execute[apt-get-update] action run (apt::default line 22)
[2015-01-05T20:22:37+00:00] INFO: execute[apt-get-update] ran successfully
[2015-01-05T20:22:37+00:00] INFO: Processing execute[apt-get-update-periodic] action run (apt::default line 52)
[2015-01-05T20:22:37+00:00] INFO: Processing directory[/var/cache/local] action create (apt::default line 62)
[2015-01-05T20:22:37+00:00] INFO: directory[/var/cache/local] created directory /var/cache/local
[2015-01-05T20:22:38+00:00] INFO: directory[/var/cache/local] owner changed to 0
[2015-01-05T20:22:38+00:00] INFO: directory[/var/cache/local] group changed to 0
[2015-01-05T20:22:38+00:00] INFO: directory[/var/cache/local] mode changed to 755
[2015-01-05T20:22:38+00:00] INFO: Processing directory[/var/cache/local/preseeding] action create (apt::default line 62)
[2015-01-05T20:22:38+00:00] INFO: directory[/var/cache/local/preseeding] created directory /var/cache/local/preseeding
[2015-01-05T20:22:38+00:00] INFO: directory[/var/cache/local/preseeding] owner changed to 0
[2015-01-05T20:22:38+00:00] INFO: directory[/var/cache/local/preseeding] group changed to 0
[2015-01-05T20:22:38+00:00] INFO: directory[/var/cache/local/preseeding] mode changed to 755
[2015-01-05T20:22:38+00:00] INFO: Processing package[autoconf] action install (build-essential::_debian line 21)
[2015-01-05T20:22:41+00:00] INFO: Processing package[binutils-doc] action install (build-essential::_debian line 22)
[2015-01-05T20:22:43+00:00] INFO: Processing package[bison] action install (build-essential::_debian line 23)
[2015-01-05T20:22:45+00:00] INFO: Processing package[build-essential] action install (build-essential::_debian line 24)
[2015-01-05T20:23:10+00:00] INFO: Processing package[flex] action install (build-essential::_debian line 25)
[2015-01-05T20:23:12+00:00] INFO: Processing package[gettext] action install (build-essential::_debian line 26)
[2015-01-05T20:23:16+00:00] INFO: Processing package[ncurses-dev] action install (build-essential::_debian line 27)
[2015-01-05T20:23:16+00:00] INFO: package[ncurses-dev] is a virtual package, actually acting on package[libncurses5-dev]
[2015-01-05T20:23:18+00:00] INFO: Processing package[python] action install (python::package line 40)
[2015-01-05T20:23:19+00:00] INFO: Processing package[python-dev] action install (python::package line 40)
[2015-01-05T20:23:26+00:00] INFO: Processing cookbook_file[/tmp/heat_chef/ez_setup.py] action create (python::pip line 36)
[2015-01-05T20:23:26+00:00] INFO: cookbook_file[/tmp/heat_chef/ez_setup.py] created file /tmp/heat_chef/ez_setup.py
[2015-01-05T20:23:26+00:00] INFO: cookbook_file[/tmp/heat_chef/ez_setup.py] updated file contents /tmp/heat_chef/ez_setup.py
[2015-01-05T20:23:26+00:00] INFO: cookbook_file[/tmp/heat_chef/ez_setup.py] mode changed to 644
[2015-01-05T20:23:26+00:00] INFO: Processing cookbook_file[/tmp/heat_chef/get-pip.py] action create (python::pip line 42)
[2015-01-05T20:23:26+00:00] INFO: cookbook_file[/tmp/heat_chef/get-pip.py] created file /tmp/heat_chef/get-pip.py
[2015-01-05T20:23:26+00:00] INFO: cookbook_file[/tmp/heat_chef/get-pip.py] updated file contents /tmp/heat_chef/get-pip.py
[2015-01-05T20:23:26+00:00] INFO: cookbook_file[/tmp/heat_chef/get-pip.py] mode changed to 644
[2015-01-05T20:23:26+00:00] INFO: Processing execute[install-setuptools] action run (python::pip line 48)
[2015-01-05T20:23:28+00:00] INFO: execute[install-setuptools] ran successfully
[2015-01-05T20:23:28+00:00] INFO: Processing execute[install-pip] action run (python::pip line 56)
[2015-01-05T20:23:30+00:00] INFO: execute[install-pip] ran successfully
[2015-01-05T20:23:30+00:00] INFO: Processing python_pip[virtualenv] action install (python::virtualenv line 23)
[2015-01-05T20:23:31+00:00] INFO: Installing python_pip[virtualenv] version latest
[2015-01-05T20:23:32+00:00] INFO: Processing package[build-essential] action install (ipynb::default line 29)
[2015-01-05T20:23:32+00:00] INFO: Processing package[libcurl4-openssl-dev] action install (ipynb::default line 29)
[2015-01-05T20:23:45+00:00] INFO: Processing package[libssl-dev] action install (ipynb::default line 29)
[2015-01-05T20:23:46+00:00] INFO: Processing package[zlib1g-dev] action install (ipynb::default line 29)
[2015-01-05T20:23:46+00:00] INFO: Processing package[libpcre3-dev] action install (ipynb::default line 29)
[2015-01-05T20:23:52+00:00] INFO: Processing package[gfortran] action install (ipynb::default line 29)
[2015-01-05T20:23:56+00:00] INFO: Processing package[libblas-dev] action install (ipynb::default line 29)
[2015-01-05T20:23:58+00:00] INFO: Processing package[libblas3gf] action install (ipynb::default line 29)
[2015-01-05T20:24:00+00:00] INFO: Processing package[liblapack3gf] action install (ipynb::default line 29)
[2015-01-05T20:24:03+00:00] INFO: Processing package[liblapack-dev] action install (ipynb::default line 29)
[2015-01-05T20:24:06+00:00] INFO: Processing package[libncurses5-dev] action install (ipynb::default line 29)
[2015-01-05T20:24:06+00:00] INFO: Processing package[libatlas-dev] action install (ipynb::default line 29)
[2015-01-05T20:24:08+00:00] INFO: Processing package[libatlas-base-dev] action install (ipynb::default line 29)
[2015-01-05T20:24:13+00:00] INFO: Processing package[libscalapack-mpi1] action install (ipynb::default line 29)
[2015-01-05T20:24:19+00:00] INFO: Processing package[libscalapack-pvm1] action install (ipynb::default line 29)
[2015-01-05T20:24:23+00:00] INFO: Processing package[liblcms-utils] action install (ipynb::default line 29)
[2015-01-05T20:24:26+00:00] INFO: Processing package[python-imaging-doc] action install (ipynb::default line 29)
[2015-01-05T20:24:28+00:00] INFO: Processing package[python-imaging-dbg] action install (ipynb::default line 29)
[2015-01-05T20:24:37+00:00] INFO: Processing package[libamd2.3.1] action install (ipynb::default line 29)
[2015-01-05T20:24:39+00:00] INFO: Processing package[libjpeg-turbo8] action install (ipynb::default line 29)
[2015-01-05T20:24:39+00:00] INFO: Processing package[libjpeg8] action install (ipynb::default line 29)
[2015-01-05T20:24:39+00:00] INFO: Processing package[liblcms1] action install (ipynb::default line 29)
[2015-01-05T20:24:39+00:00] INFO: Processing package[libumfpack5.6.2] action install (ipynb::default line 29)
[2015-01-05T20:24:42+00:00] INFO: Processing package[python-imaging] action install (ipynb::default line 29)
[2015-01-05T20:24:43+00:00] INFO: Processing package[libpng12-0] action install (ipynb::default line 29)
[2015-01-05T20:24:43+00:00] INFO: Processing package[libpng12-dev] action install (ipynb::default line 29)
[2015-01-05T20:24:48+00:00] INFO: Processing package[libfreetype6] action install (ipynb::default line 29)
[2015-01-05T20:24:49+00:00] INFO: Processing package[libfreetype6-dev] action install (ipynb::default line 29)
[2015-01-05T20:24:51+00:00] INFO: Processing package[libcurl4-gnutls-dev] action install (ipynb::default line 29)
[2015-01-05T20:24:55+00:00] INFO: Processing package[python-pycurl-dbg] action install (ipynb::default line 29)
[2015-01-05T20:24:57+00:00] INFO: Processing package[git-core] action install (ipynb::default line 29)
[2015-01-05T20:24:59+00:00] INFO: Processing package[cython] action install (ipynb::default line 29)
[2015-01-05T20:25:03+00:00] INFO: Processing package[libhdf5-7] action install (ipynb::default line 29)
[2015-01-05T20:25:06+00:00] INFO: Processing package[libhdf5-serial-dev] action install (ipynb::default line 29)
[2015-01-05T20:25:11+00:00] INFO: Processing package[python-egenix-mxdatetime] action install (ipynb::default line 29)
[2015-01-05T20:25:13+00:00] INFO: Processing package[vim] action install (ipynb::default line 29)
[2015-01-05T20:25:18+00:00] INFO: Processing package[python-numpy] action install (ipynb::default line 29)
[2015-01-05T20:25:22+00:00] INFO: Processing package[python-scipy] action install (ipynb::default line 29)
[2015-01-05T20:25:27+00:00] INFO: Processing package[pandoc] action install (ipynb::default line 29)
[2015-01-05T20:25:33+00:00] INFO: Processing group[ipynb] action create (ipynb::default line 35)
[2015-01-05T20:25:33+00:00] INFO: group[ipynb] created
[2015-01-05T20:25:33+00:00] INFO: Processing user[ipynb] action create (ipynb::default line 41)
[2015-01-05T20:25:33+00:00] INFO: user[ipynb] created
[2015-01-05T20:25:33+00:00] INFO: Processing python_virtualenv[/home/ipynb/.ipyvirt] action create (ipynb::default line 51)
[2015-01-05T20:25:33+00:00] INFO: Creating virtualenv python_virtualenv[/home/ipynb/.ipyvirt] at /home/ipynb/.ipyvirt
[2015-01-05T20:25:33+00:00] INFO: Processing directory[/home/ipynb/.ipyvirt] action create (/tmp/heat_chef/b957b1a6-bf3d-4abe-a327-189feac23b14/cookbooks/python/providers/virtualenv.rb line 31)
[2015-01-05T20:25:33+00:00] INFO: directory[/home/ipynb/.ipyvirt] created directory /home/ipynb/.ipyvirt
[2015-01-05T20:25:33+00:00] INFO: directory[/home/ipynb/.ipyvirt] owner changed to 1001
[2015-01-05T20:25:33+00:00] INFO: directory[/home/ipynb/.ipyvirt] group changed to 1001
[2015-01-05T20:25:33+00:00] INFO: Processing execute[virtualenv --python=python2.7  /home/ipynb/.ipyvirt] action run (/tmp/heat_chef/b957b1a6-bf3d-4abe-a327-189feac23b14/cookbooks/python/providers/virtualenv.rb line 37)
[2015-01-05T20:25:35+00:00] INFO: execute[virtualenv --python=python2.7  /home/ipynb/.ipyvirt] ran successfully
[2015-01-05T20:25:35+00:00] INFO: Processing python_pip[uwsgi] action install (ipynb::default line 59)
[2015-01-05T20:25:36+00:00] INFO: Installing python_pip[uwsgi] version latest
[2015-01-05T20:26:04+00:00] INFO: Processing python_pip[numpy==1.8.0] action install (ipynb::default line 68)
[2015-01-05T20:26:05+00:00] INFO: Installing python_pip[numpy==1.8.0] version latest
[2015-01-05T20:28:00+00:00] INFO: Processing python_pip[freetype-py==0.4.1] action install (ipynb::default line 68)
[2015-01-05T20:28:01+00:00] INFO: Installing python_pip[freetype-py==0.4.1] version latest
[2015-01-05T20:28:02+00:00] INFO: Processing python_pip[pillow==2.3.0] action install (ipynb::default line 68)
[2015-01-05T20:28:03+00:00] INFO: Installing python_pip[pillow==2.3.0] version latest
[2015-01-05T20:28:25+00:00] INFO: Processing python_pip[scipy==0.13.2] action install (ipynb::default line 68)
[2015-01-05T20:28:25+00:00] INFO: Installing python_pip[scipy==0.13.2] version latest
[2015-01-05T20:38:24+00:00] INFO: Processing python_pip[python-dateutil] action install (ipynb::default line 68)
[2015-01-05T20:38:25+00:00] INFO: Installing python_pip[python-dateutil] version latest
[2015-01-05T20:38:26+00:00] INFO: Processing python_pip[pytz==2013b] action install (ipynb::default line 68)
[2015-01-05T20:38:27+00:00] INFO: Installing python_pip[pytz==2013b] version latest
[2015-01-05T20:38:29+00:00] INFO: Processing python_pip[six==1.5.2] action install (ipynb::default line 68)
[2015-01-05T20:38:30+00:00] INFO: Installing python_pip[six==1.5.2] version latest
[2015-01-05T20:38:31+00:00] INFO: Processing python_pip[scikit-learn==0.14.1] action install (ipynb::default line 68)
[2015-01-05T20:38:32+00:00] INFO: Installing python_pip[scikit-learn==0.14.1] version latest
[2015-01-05T20:40:23+00:00] INFO: Processing python_pip[pandas==0.12.0] action install (ipynb::default line 68)
[2015-01-05T20:40:23+00:00] INFO: Installing python_pip[pandas==0.12.0] version latest
[2015-01-05T20:42:56+00:00] INFO: Processing python_pip[matplotlib==1.4.2] action install (ipynb::default line 68)
[2015-01-05T20:42:56+00:00] INFO: Installing python_pip[matplotlib==1.4.2] version latest
[2015-01-05T20:44:46+00:00] INFO: Processing python_pip[pygments==1.6] action install (ipynb::default line 68)
[2015-01-05T20:44:47+00:00] INFO: Installing python_pip[pygments==1.6] version latest
[2015-01-05T20:44:50+00:00] INFO: Processing python_pip[readline==6.2.4.1] action install (ipynb::default line 68)
[2015-01-05T20:44:51+00:00] INFO: Installing python_pip[readline==6.2.4.1] version latest
[2015-01-05T20:45:19+00:00] INFO: Processing python_pip[nose==1.3.0] action install (ipynb::default line 68)
[2015-01-05T20:45:19+00:00] INFO: Installing python_pip[nose==1.3.0] version latest
[2015-01-05T20:45:21+00:00] INFO: Processing python_pip[pexpect==3.0] action install (ipynb::default line 68)
[2015-01-05T20:45:22+00:00] INFO: Installing python_pip[pexpect==3.0] version latest
[2015-01-05T20:45:24+00:00] INFO: Processing python_pip[cython==0.19.2] action install (ipynb::default line 68)
[2015-01-05T20:45:24+00:00] INFO: Installing python_pip[cython==0.19.2] version latest
[2015-01-05T20:46:56+00:00] INFO: Processing python_pip[networkx==1.8.1] action install (ipynb::default line 68)
[2015-01-05T20:46:57+00:00] INFO: Installing python_pip[networkx==1.8.1] version latest
[2015-01-05T20:47:00+00:00] INFO: Processing python_pip[numexpr==2.2.2] action install (ipynb::default line 68)
[2015-01-05T20:47:00+00:00] INFO: Installing python_pip[numexpr==2.2.2] version latest
[2015-01-05T20:47:19+00:00] INFO: Processing python_pip[tables==3.0.0] action install (ipynb::default line 68)
[2015-01-05T20:47:19+00:00] INFO: Installing python_pip[tables==3.0.0] version latest
[2015-01-05T20:47:56+00:00] INFO: Processing python_pip[patsy==0.2.1] action install (ipynb::default line 68)
[2015-01-05T20:47:57+00:00] INFO: Installing python_pip[patsy==0.2.1] version latest
[2015-01-05T20:47:59+00:00] INFO: Processing python_pip[statsmodels==0.5.0] action install (ipynb::default line 68)
[2015-01-05T20:48:00+00:00] INFO: Installing python_pip[statsmodels==0.5.0] version latest
[2015-01-05T20:48:15+00:00] INFO: Processing python_pip[sympy==0.7.4.1] action install (ipynb::default line 68)
[2015-01-05T20:48:16+00:00] INFO: Installing python_pip[sympy==0.7.4.1] version latest
[2015-01-05T20:48:26+00:00] INFO: Processing python_pip[scikit-image==0.9.3] action install (ipynb::default line 68)
[2015-01-05T20:48:27+00:00] INFO: Installing python_pip[scikit-image==0.9.3] version latest
[2015-01-05T20:51:25+00:00] INFO: Processing python_pip[nltk==2.0.4] action install (ipynb::default line 68)
[2015-01-05T20:51:26+00:00] INFO: Installing python_pip[nltk==2.0.4] version latest
[2015-01-05T20:51:29+00:00] INFO: Running queued delayed notifications before re-raising exception
[2015-01-05T20:51:29+00:00] ERROR: Running exception handlers
[2015-01-05T20:51:29+00:00] ERROR: Exception handlers complete
[2015-01-05T20:51:29+00:00] FATAL: Stacktrace dumped to /tmp/heat_chef/chef-stacktrace.out
[2015-01-05T20:51:29+00:00] ERROR: python_pip[nltk==2.0.4] (ipynb::default line 68) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
---- Begin output of /home/ipynb/.ipyvirt/bin/pip install  nltk==2.0.4 ----
STDOUT: Collecting nltk==2.0.4
  Downloading nltk-2.0.4.tar.gz (955kB)
    Downloading http://pypi.python.org/packages/source/d/distribute/distribute-0.6.21.tar.gz
    Extracting in /tmp/tmpfsS2eZ
    Now working in /tmp/tmpfsS2eZ/distribute-0.6.21
    Building a Distribute egg in /tmp/pip-build-3KoeBi/nltk
    /tmp/pip-build-3KoeBi/nltk/distribute-0.6.21-py2.7.egg
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-3KoeBi/nltk/setup.py", line 32, in <module>
        del sdist.finders[:]
    AttributeError: 'module' object has no attribute 'finders'
    Complete output from command python setup.py egg_info:
    Downloading http://pypi.python.org/packages/source/d/distribute/distribute-0.6.21.tar.gz

    Extracting in /tmp/tmpfsS2eZ

    Now working in /tmp/tmpfsS2eZ/distribute-0.6.21

    Building a Distribute egg in /tmp/pip-build-3KoeBi/nltk

    /tmp/pip-build-3KoeBi/nltk/distribute-0.6.21-py2.7.egg

    Traceback (most recent call last):

      File "<string>", line 20, in <module>

      File "/tmp/pip-build-3KoeBi/nltk/setup.py", line 32, in <module>

        del sdist.finders[:]

    AttributeError: 'module' object has no attribute 'finders'

    ----------------------------------------
    Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-3KoeBi/nltk
STDERR:
---- End output of /home/ipynb/.ipyvirt/bin/pip install  nltk==2.0.4 ----
Ran /home/ipynb/.ipyvirt/bin/pip install  nltk==2.0.4 returned 1
[2015-01-05T20:51:29+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```

**Comment by JasonBoyles** [comment]
fixed by https://github.com/rgbkrk/ipython-notebook-cookbook/issues/14
